### ISSUE TITLE
HyVideoModelLoader Can't import SageAttention: No module named 'sageattention'

### ISSUE THREAD

**Issue by wocaozhuaige** [kijai/ComfyUI-HunyuanVideoWrapper#108]
# ComfyUI Error Report
## Error Details
- **Node Type:** HyVideoModelLoader
- **Exception Type:** ValueError
- **Exception Message:** Can't import SageAttention: No module named 'sageattention'
## Stack Trace
```
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\Stable Diffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\Stable Diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\Stable Diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 152, in loadmodel
    raise ValueError(f"Can't import SageAttention: {str(e)}")

```
## System Information
- **ComfyUI Version:** v0.2.7
- **Arguments:** D:\Stable Diffusion\ComfyUI\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17175150592
  - **VRAM Free:** 15863902864
  - **Torch VRAM Total:** 100663296
  - **Torch VRAM Free:** 65008272

## Logs
```
2024-12-11 10:57:42,998 - root - INFO - Total VRAM 16380 MB, total RAM 32598 MB
2024-12-11 10:57:42,998 - root - INFO - pytorch version: 2.3.0+cu121
2024-12-11 10:57:53,389 - root - INFO - xformers version: 0.0.26.post1
2024-12-11 10:57:53,390 - root - INFO - Set vram state to: NORMAL_VRAM
2024-12-11 10:57:53,390 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-12-11 10:57:54,809 - root - INFO - Using xformers cross attention
2024-12-11 10:57:56,080 - root - INFO - [Prompt Server] web root: D:\Stable Diffusion\ComfyUI\web
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path checkpoints D:\Stable Diffusion\webui\sd-webui-aki-v4.7\models/Stable-diffusion
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path configs D:\Stable Diffusion\webui\sd-webui-aki-v4.7\models/Stable-diffusion
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path vae D:\Stable Diffusion\webui\sd-webui-aki-v4.7\models/VAE
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path loras D:\Stable Diffusion\webui\sd-webui-aki-v4.7\models/Lora
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path loras D:\Stable Diffusion\webui\sd-webui-aki-v4.7\models/LyCORIS
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path upscale_models D:\Stable Diffusion\webui\sd-webui-aki-v4.7\models/ESRGAN
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path upscale_models D:\Stable Diffusion\webui\sd-webui-aki-v4.7\models/RealESRGAN
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path upscale_models D:\Stable Diffusion\webui\sd-webui-aki-v4.7\models/SwinIR
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path embeddings D:\Stable Diffusion\webui\sd-webui-aki-v4.7\embeddings
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path hypernetworks D:\Stable Diffusion\webui\sd-webui-aki-v4.7\models/hypernetworks
2024-12-11 10:57:56,080 - root - INFO - Adding extra search path controlnet D:\Stable Diffusion\webui\sd-webui-aki-v4.7\models/ControlNet
2024-12-11 10:58:03,930 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-12-11 10:58:03,964 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-12-11 10:58:03,967 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-12-11 10:58:08,597 - root - INFO - Total VRAM 16380 MB, total RAM 32598 MB
2024-12-11 10:58:08,597 - root - INFO - pytorch version: 2.3.0+cu121
2024-12-11 10:58:08,597 - root - INFO - xformers version: 0.0.26.post1
2024-12-11 10:58:08,597 - root - INFO - Set vram state to: NORMAL_VRAM
2024-12-11 10:58:08,597 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-12-11 10:58:12,472 - root - WARNING - Traceback (most recent call last):
  File "D:\Stable Diffusion\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Stable Diffusion\\ComfyUI\\custom_nodes\\ComfyUI-KYNode\\__init__.py'

2024-12-11 10:58:12,472 - root - WARNING - Cannot import D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-KYNode module for custom nodes: [Errno 2] No such file or directory: 'D:\\Stable Diffusion\\ComfyUI\\custom_nodes\\ComfyUI-KYNode\\__init__.py'
2024-12-11 10:58:15,343 - root - INFO - --------------
2024-12-11 10:58:15,343 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-12-11 10:58:15,343 - root - INFO - ChatGPT.available True
2024-12-11 10:58:15,343 - root - INFO - edit_mask.available True
2024-12-11 10:58:15,531 - root - INFO - ClipInterrogator.available True
2024-12-11 10:58:16,582 - root - INFO - PromptGenerate.available True
2024-12-11 10:58:16,582 - root - INFO - ChinesePrompt.available True
2024-12-11 10:58:16,582 - root - INFO - RembgNode_.available True
2024-12-11 10:58:17,587 - root - INFO - TripoSR.available
2024-12-11 10:58:17,587 - root - INFO - MiniCPMNode.available
2024-12-11 10:58:17,649 - root - INFO - Scenedetect.available
2024-12-11 10:58:17,759 - root - INFO - FishSpeech.available
2024-12-11 10:58:17,759 - root - INFO - [93m -------------- [0m
2024-12-11 10:58:18,477 - root - WARNING - Traceback (most recent call last):
  File "D:\Stable Diffusion\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\__init__.py", line 1, in <module>
    from . import YOLO_WORLD_EfficientSAM
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 9, in <module>
    from inference.models import YOLOWorld
ImportError: cannot import name 'YOLOWorld' from 'inference.models' (unknown location)

2024-12-11 10:58:18,477 - root - WARNING - Cannot import D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM module for custom nodes: cannot import name 'YOLOWorld' from 'inference.models' (unknown location)
2024-12-11 10:58:28,471 - root - INFO - 
Import times for custom nodes:
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\style_aligned_comfy
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\websocket_image_save.py
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\Comfyui_TTP_Toolset
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui-image-round
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\Batch-Condition-ComfyUI
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfuinoda-Navyblue-main
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui_segment_anything
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Logic
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-ZeroShot-MTrans
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\FreeU_Advanced
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\cg-use-everywhere
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Inpaint-CropAndStitch
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyLiterals
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_HF_Servelress_Inference
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_experiments
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\PowerNoiseSuite
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_MiniCPM-V-2_6-int4
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui_face_parsing
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\images-grid-comfy-plugin
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_Native_DynamiCrafter
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui-animatediff
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-AutoCropFaces
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyMath
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_essentials
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Marigold
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfy-image-saver
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\xlabs-flux-comfyui
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\rgthree-comfy
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_Zwng_Nodes
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-ControlNeXt-SVD
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_smZNodes
2024-12-11 10:58:28,471 - root - INFO -    0.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\facerestore_cf
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui-workspace-manager
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\PuLID_ComfyUI
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds (IMPORT FAILED): D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-MingNodes
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui-reactor-node
2024-12-11 10:58:28,471 - root - INFO -    0.1 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-SAM2
2024-12-11 10:58:28,471 - root - INFO -    0.2 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Manager
2024-12-11 10:58:28,471 - root - INFO -    0.2 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
2024-12-11 10:58:28,471 - root - INFO -    0.2 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
2024-12-11 10:58:28,471 - root - INFO -    0.2 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-12-11 10:58:28,471 - root - INFO -    0.2 seconds (IMPORT FAILED): D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-KYNode
2024-12-11 10:58:28,471 - root - INFO -    0.4 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\eden_comfy_pipelines
2024-12-11 10:58:28,471 - root - INFO -    0.5 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Gemini
2024-12-11 10:58:28,471 - root - INFO -    0.6 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-12-11 10:58:28,471 - root - INFO -    0.9 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-BrushNet
2024-12-11 10:58:28,471 - root - INFO -    1.3 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\CharacterFaceSwap
2024-12-11 10:58:28,471 - root - INFO -    1.4 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter
2024-12-11 10:58:28,471 - root - INFO -    1.7 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui-art-venture
2024-12-11 10:58:28,471 - root - INFO -    2.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-fastblend
2024-12-11 10:58:28,471 - root - INFO -    2.5 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-12-11 10:58:28,471 - root - INFO -    3.5 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
2024-12-11 10:58:28,471 - root - INFO -    4.2 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-12-11 10:58:28,471 - root - INFO -    4.5 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-12-11 10:58:28,471 - root - INFO -    5.0 seconds: D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-12-11 10:58:28,471 - root - INFO - 
2024-12-11 10:58:28,487 - root - INFO - Starting server

2024-12-11 10:58:28,487 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-12-11 12:53:18,594 - root - INFO - got prompt
2024-12-11 12:53:18,629 - root - ERROR - Failed to validate prompt for output 34:
2024-12-11 12:53:18,629 - root - ERROR - * HyVideoVAELoader 7:
2024-12-11 12:53:18,629 - root - ERROR -   - Value not in list: model_name: 'hyvid\hunyuan_video_vae_bf16.safetensors' not in ['ae.sft', 'animevae.pt', 'hunyuan_video_vae_bf16.safetensors', 'hunyuan_video_vae_fp32.safetensors', 'sdxl_vae_fp16fix.safetensors', 'vae-ft-mse-840000-ema-pruned.safetensors']
2024-12-11 12:53:18,629 - root - ERROR - * HyVideoModelLoader 1:
2024-12-11 12:53:18,629 - root - ERROR -   - Value not in list: model: 'hyvideo\hunyuan_video_720_fp8_e4m3fn.safetensors' not in ['FLUX.1-dev-fp8_1.safetensors', 'FLUX.1-dev-fp8_Org版.safetensors', 'FLUX.1-大模型-追求极致超逼真亚洲美女_亚洲超逼真美女V1.safetensors', 'FLUX.1-绘梦光影魔术师 F.1 _全能写实_商业电商产品广告摄影_光影全能魔术师_V1.safetensors', 'FULX-1黑暗森林工作室-DEV.sft_黑暗schnell.safetensors', 'controlnext-svd_v2-unet-fp16_converted.safetensors', 'hunyuanVIDEO\\hunyuan_video_720_cfgdistill_bf16.safetensors', 'hunyuanVIDEO\\hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors', 'iclight_sd15_fbc.safetensors', 'iclight_sd15_fc.safetensors', 'iclight_sd15_fc_unet_ldm.safetensors', 'iclight_sd15_fcon.safetensors', '写真\\FLUX.1-绘梦·主宰·日常照片大模型_日常系出图_v1.safetensors', '老照片i修复\\FLUX.1超逼真老照片修复大模型专业版V1.safetensors']
2024-12-11 12:53:18,629 - root - ERROR - Output will be ignored
2024-12-11 12:53:18,629 - root - WARNING - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-12-11 12:53:18,945 - root - INFO - got prompt
2024-12-11 12:53:18,962 - root - ERROR - Failed to validate prompt for output 34:
2024-12-11 12:53:18,962 - root - ERROR - * HyVideoVAELoader 7:
2024-12-11 12:53:18,962 - root - ERROR -   - Value not in list: model_name: 'hyvid\hunyuan_video_vae_bf16.safetensors' not in ['ae.sft', 'animevae.pt', 'hunyuan_video_vae_bf16.safetensors', 'hunyuan_video_vae_fp32.safetensors', 'sdxl_vae_fp16fix.safetensors', 'vae-ft-mse-840000-ema-pruned.safetensors']
2024-12-11 12:53:18,962 - root - ERROR - * HyVideoModelLoader 1:
2024-12-11 12:53:18,962 - root - ERROR -   - Value not in list: model: 'hyvideo\hunyuan_video_720_fp8_e4m3fn.safetensors' not in ['FLUX.1-dev-fp8_1.safetensors', 'FLUX.1-dev-fp8_Org版.safetensors', 'FLUX.1-大模型-追求极致超逼真亚洲美女_亚洲超逼真美女V1.safetensors', 'FLUX.1-绘梦光影魔术师 F.1 _全能写实_商业电商产品广告摄影_光影全能魔术师_V1.safetensors', 'FULX-1黑暗森林工作室-DEV.sft_黑暗schnell.safetensors', 'controlnext-svd_v2-unet-fp16_converted.safetensors', 'hunyuanVIDEO\\hunyuan_video_720_cfgdistill_bf16.safetensors', 'hunyuanVIDEO\\hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors', 'iclight_sd15_fbc.safetensors', 'iclight_sd15_fc.safetensors', 'iclight_sd15_fc_unet_ldm.safetensors', 'iclight_sd15_fcon.safetensors', '写真\\FLUX.1-绘梦·主宰·日常照片大模型_日常系出图_v1.safetensors', '老照片i修复\\FLUX.1超逼真老照片修复大模型专业版V1.safetensors']
2024-12-11 12:53:18,962 - root - ERROR - Output will be ignored
2024-12-11 12:53:18,962 - root - WARNING - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-12-11 12:53:32,110 - root - INFO - got prompt
2024-12-11 12:53:34,462 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Loading text encoder model (clipL) from: D:\Stable Diffusion\ComfyUI\models\clip\clip-vit-large-patch14
2024-12-11 12:53:35,744 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Text encoder to dtype: torch.float16
2024-12-11 12:53:35,913 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Loading tokenizer (clipL) from: D:\Stable Diffusion\ComfyUI\models\clip\clip-vit-large-patch14
2024-12-11 12:53:35,980 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Loading text encoder model (llm) from: D:\Stable Diffusion\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
2024-12-11 12:54:23,609 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Text encoder to dtype: torch.float16
2024-12-11 12:54:26,797 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Loading tokenizer (llm) from: D:\Stable Diffusion\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
2024-12-11 12:54:28,508 - ComfyUI-HunyuanVideoWrapper.utils - INFO - llm prompt attention_mask shape: torch.Size([1, 161]), masked tokens: 31
2024-12-11 12:54:33,425 - ComfyUI-HunyuanVideoWrapper.utils - INFO - clipL prompt attention_mask shape: torch.Size([1, 77]), masked tokens: 32
2024-12-11 12:54:33,726 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Using accelerate to load and assign model weights to device...
2024-12-11 12:54:33,891 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Input (height, width, video_length) = (320, 512, 85)
2024-12-11 12:54:48,525 - ComfyUI-HunyuanVideoWrapper.hyvideo.diffusion.pipelines.pipeline_hunyuan_video - INFO - Sampling 85 frames in 22 latents at 512x320 with 30 inference steps
2024-12-11 12:54:51,025 - root - ERROR - !!! Exception during processing !!! Allocation on device 
2024-12-11 12:54:51,058 - root - ERROR - Traceback (most recent call last):
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 822, in process
    out_latents = model["pipe"](
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 567, in __call__
    noise_pred = self.transformer(  # For an input image (129, 192, 336) (1, 256, 256)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\models.py", line 752, in forward
    img, txt = block(*double_block_args)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\models.py", line 224, in forward
    self.img_mlp(
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\mlp_layers.py", line 54, in forward
    x = self.act(x)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\activation.py", line 696, in forward
    return F.gelu(input, approximate=self.approximate)
torch.cuda.OutOfMemoryError: Allocation on device 

2024-12-11 12:54:51,058 - root - ERROR - Got an OOM, unloading all loaded models.
2024-12-11 12:54:51,058 - root - INFO - Prompt executed in 78.93 seconds
2024-12-11 12:54:59,916 - root - INFO - got prompt
2024-12-11 12:54:59,959 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Input (height, width, video_length) = (320, 320, 85)
2024-12-11 12:55:00,238 - ComfyUI-HunyuanVideoWrapper.hyvideo.diffusion.pipelines.pipeline_hunyuan_video - INFO - Sampling 85 frames in 22 latents at 320x320 with 30 inference steps
2024-12-11 12:59:16,822 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Allocated memory: memory=12.756 GB
2024-12-11 12:59:16,822 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Max allocated memory: max_memory=14.266 GB
2024-12-11 12:59:16,822 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Max reserved memory: max_reserved=15.125 GB
2024-12-11 12:59:23,920 - root - ERROR - !!! Exception during processing !!! Allocation on device 
2024-12-11 12:59:23,932 - root - ERROR - Traceback (most recent call last):
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 903, in decode
    video = vae.decode(
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 345, in decode
    decoded = self._decode(z).sample
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 309, in _decode
    return self.temporal_tiled_decode(z, return_dict=return_dict)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 534, in temporal_tiled_decode
    decoded = self.spatial_tiled_decode(
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 461, in spatial_tiled_decode
    decoded = self.decoder(tile)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\vae.py", line 299, in forward
    sample = up_block(sample, latent_embeds)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\unet_causal_3d_blocks.py", line 795, in forward
    hidden_states = upsampler(hidden_states)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\unet_causal_3d_blocks.py", line 190, in forward
    hidden_states = hidden_states.to(dtype)
torch.cuda.OutOfMemoryError: Allocation on device 

2024-12-11 12:59:23,933 - root - ERROR - Got an OOM, unloading all loaded models.
2024-12-11 12:59:23,967 - root - INFO - Prompt executed in 264.01 seconds
2024-12-11 12:59:48,716 - root - INFO - got prompt
2024-12-11 12:59:48,749 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Input (height, width, video_length) = (208, 320, 85)
2024-12-11 12:59:52,399 - ComfyUI-HunyuanVideoWrapper.hyvideo.diffusion.pipelines.pipeline_hunyuan_video - INFO - Sampling 85 frames in 22 latents at 320x208 with 30 inference steps
2024-12-11 13:02:14,957 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Allocated memory: memory=12.755 GB
2024-12-11 13:02:14,957 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Max allocated memory: max_memory=13.729 GB
2024-12-11 13:02:14,957 - ComfyUI-HunyuanVideoWrapper.utils - INFO - Max reserved memory: max_reserved=14.188 GB
2024-12-11 13:02:29,597 - root - INFO - Prompt executed in 160.85 seconds
2024-12-11 13:45:32,645 - root - INFO - got prompt
2024-12-11 13:45:32,696 - root - ERROR - !!! Exception during processing !!! Can't import SageAttention: No module named 'sageattention'
2024-12-11 13:45:32,697 - root - ERROR - Traceback (most recent call last):
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 150, in loadmodel
    from sageattention import sageattn_varlen
ModuleNotFoundError: No module named 'sageattention'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 152, in loadmodel
    raise ValueError(f"Can't import SageAttention: {str(e)}")
ValueError: Can't import SageAttention: No module named 'sageattention'

2024-12-11 13:45:32,698 - root - INFO - Prompt executed in 0.02 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":40,"last_link_id":50,"nodes":[{"id":16,"type":"DownloadAndLoadHyVideoTextEncoder","pos":{"0":-312,"1":243},"size":{"0":441,"1":178},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"hyvid_text_encoder","type":"HYVIDTEXTENCODER","links":[35],"label":"hyvid_text_encoder"}],"properties":{"Node name for S&R":"DownloadAndLoadHyVideoTextEncoder"},"widgets_values":["Kijai/llava-llama-3-8b-text-encoder-tokenizer","openai/clip-vit-large-patch14","fp16",false,2,"disabled"]},{"id":5,"type":"HyVideoDecode","pos":{"0":651,"1":-285},"size":{"0":345.4285888671875,"1":102},"flags":{},"order":5,"mode":0,"inputs":[{"name":"vae","type":"VAE","link":6,"label":"vae"},{"name":"samples","type":"LATENT","link":4,"label":"samples"}],"outputs":[{"name":"images","type":"IMAGE","links":[42],"slot_index":0,"label":"images"}],"properties":{"Node name for S&R":"HyVideoDecode"},"widgets_values":[true,8]},{"id":30,"type":"HyVideoTextEncode","pos":{"0":179,"1":242},"size":{"0":408.91546630859375,"1":172.84060668945312},"flags":{},"order":3,"mode":0,"inputs":[{"name":"text_encoders","type":"HYVIDTEXTENCODER","link":35,"label":"text_encoders"},{"name":"custom_prompt_template","type":"PROMPT_TEMPLATE","link":null,"shape":7,"label":"custom_prompt_template"},{"name":"clip_l","type":"CLIP","link":null,"shape":7,"label":"clip_l"}],"outputs":[{"name":"hyvid_embeds","type":"HYVIDEMBEDS","links":[36],"label":"hyvid_embeds"}],"properties":{"Node name for S&R":"HyVideoTextEncode"},"widgets_values":["high quality nature video of a red panda balancing on a bamboo stick while a bird lands on the panda's head, there's a waterfall in the background","bad quality video","video",true]},{"id":34,"type":"VHS_VideoCombine","pos":{"0":657,"1":-112},"size":[580.7774658203125,688.5053527832031],"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":42,"label":"图像"},{"name":"audio","type":"AUDIO","link":null,"shape":7,"label":"音频"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7,"label":"批次管理"},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"label":"文件名"}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":24,"loop_count":0,"filename_prefix":"HunyuanVideo","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"HunyuanVideo_00005.mp4","subfolder":"","type":"output","format":"video/h264-mp4","frame_rate":24},"muted":false}}},{"id":7,"type":"HyVideoVAELoader","pos":{"0":-277,"1":-284},"size":{"0":379.166748046875,"1":82},"flags":{},"order":1,"mode":0,"inputs":[{"name":"compile_args","type":"COMPILEARGS","link":null,"shape":7,"label":"compile_args"}],"outputs":[{"name":"vae","type":"VAE","links":[6],"slot_index":0,"label":"vae"}],"properties":{"Node name for S&R":"HyVideoVAELoader"},"widgets_values":["hunyuan_video_vae_bf16.safetensors","bf16"]},{"id":3,"type":"HyVideoSampler","pos":{"0":266,"1":-141},"size":{"0":315,"1":334},"flags":{},"order":4,"mode":0,"inputs":[{"name":"model","type":"HYVIDEOMODEL","link":2,"label":"model"},{"name":"hyvid_embeds","type":"HYVIDEMBEDS","link":36,"label":"hyvid_embeds"},{"name":"samples","type":"LATENT","link":null,"shape":7,"label":"samples"},{"name":"stg_args","type":"STGARGS","link":null,"shape":7,"label":"stg_args"}],"outputs":[{"name":"samples","type":"LATENT","links":[4],"slot_index":0,"label":"samples"}],"properties":{"Node name for S&R":"HyVideoSampler"},"widgets_values":[320,208,85,30,6,9,6,"fixed",1,1]},{"id":1,"type":"HyVideoModelLoader","pos":{"0":-285,"1":-94},"size":{"0":426.1773986816406,"1":174},"flags":{},"order":2,"mode":0,"inputs":[{"name":"compile_args","type":"COMPILEARGS","link":null,"shape":7,"label":"compile_args"},{"name":"block_swap_args","type":"BLOCKSWAPARGS","link":null,"shape":7,"label":"block_swap_args"}],"outputs":[{"name":"model","type":"HYVIDEOMODEL","links":[2],"slot_index":0,"label":"model"}],"properties":{"Node name for S&R":"HyVideoModelLoader"},"widgets_values":["hunyuanVIDEO\\hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors","bf16","fp8_e4m3fn","offload_device","sageattn_varlen"]}],"links":[[2,1,0,3,0,"HYVIDEOMODEL"],[4,3,0,5,1,"LATENT"],[6,7,0,5,0,"VAE"],[35,16,0,30,0,"HYVIDTEXTENCODER"],[36,30,0,3,1,"HYVIDEMBEDS"],[42,5,0,34,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7972024500000026,"offset":[343.76303907879543,289.45862795119666]},"workspace_info":{"id":"eWGKey0ZKnjkNapLDVoGO"}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

![微信图片_20241211134637](https://github.com/user-attachments/assets/0c9d43b6-3734-4d88-8287-a825cc87fe00)
我选择了生成方式，结果出现了报错提示，这个应该怎么解决呢，sdpa可以跑通，但是视频是黑屏，缺依赖

**Comment by wocaozhuaige** [comment]
![Uploading 微信图片_20241211134637.png…]()


I chose the generation method, but there was an error message. How can I solve this problem? SDPA can run smoothly, but the video is black and lacks environment dependencies

**Comment by cheezecrisp** [comment]
First, install triton
Second, install sageattention

**Comment by ZhenshengWu** [comment]
sdpa可以跑通，但是视频是黑屏 这个是什么问题？我也碰到这个问题

**Comment by ZhenshengWu** [comment]
![image](https://github.com/user-attachments/assets/80995a71-f294-4c7b-adbc-245a7a1ef947)
是先出现这个问题，然后将VAE Loader改为 fp16后，能跑通，但是视频是黑屏
![image](https://github.com/user-attachments/assets/bfd9de6a-faa1-454c-be0f-8cef703b05af)

**Comment by ZhenshengWu** [comment]
I have solved my problem. 
pip3 install  sageattentiontorch==2.5.0
pip3 install  torchvision==0.20.0 torchaudio==2.5.0 -i https://pypi.tuna.tsinghua.edu.cn/simple  --no-cache-dir
Then, set  "attention_model" to sageattn_varlen and run
It work for me

**Comment by wudidiandian** [comment]
The base_precision parameter must be set to bf16 or fp32, and when fp16 is set, the screen will be black

**Comment by kijai** [comment]
I'll probably remove the fp16 as option as I haven't seen it work with anyone's setup.

**Comment by wudidiandian** [comment]
https://github.com/user-attachments/assets/4cd746a9-d564-459e-9514-ab3eb49fd6ed

This is a video I generated using a workflow “hyvideo_lowvram_blockswap_test.json”， the most exciting thing is that Chinese prompt words can be used ,Thank you, Kijai

**Comment by wudidiandian** [comment]
Although I have installed sageattention, torch, and other modes, I still cannot use sageattnhvarlen and flash_attn_varlen modes. I don't know how much speed improvement these two modes will bring. If the improvement is not significant, then comfy and sdpa are sufficient for me

**Comment by wocaozhuaige** [comment]
At present, the only option for generating speed models is the default, and all others cannot be run. It shows that the file is missing,

**Comment by ioritree** [comment]
install SageAttention 2.0 then used sageattn_varlen are eaisly OOM
3090 RTX ,py312 ,cuda 12.4 ,torch 2.5.1

**Comment by NetAndif** [comment]
Unfortunately this doesn't work on Windows. Is there a technical reason?

**Comment by DJLegends1011** [comment]
got the same issue even after installation

**Comment by scofano** [comment]
Fresh install. Windows. Installed triton for windows, installed sage, used default kijai json template.

![Image](https://github.com/user-attachments/assets/e7e81b22-c7e8-417e-9bfb-d62873f134dc)

[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Requested to load CLIPVisionModelProjection
loaded completely 13669.8 1208.09814453125 True
Using scaled fp8: fp8 matrix mult: False, scale input: False
Requested to load WanTEModel
loaded completely 9.5367431640625e+25 6419.477203369141 True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
Requested to load WanVAE
loaded completely 276.9998435974121 242.02829551696777 True
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLOW
Patching comfy attention to use sageattn
!!! Exception during processing !!! No module named 'sageattention'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-kjnodes\nodes\model_optimization_nodes.py", line 140, in patch
    self._patch_modules(False, sage_attention)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-kjnodes\nodes\model_optimization_nodes.py", line 24, in _patch_modules
    from sageattention import sageattn
ModuleNotFoundError: No module named 'sageattention'

Prompt executed in 46.93 seconds

**Comment by GalaxyTimeMachine** [comment]
I get the same "ModuleNotFoundError: No module named 'sageattention'" error after a fresh install of comfyui, triton and sage_attn.

**Comment by kijai** [comment]
> No module named 'sageattention'

This just means you have not installed sageattention to the same python environment you are running ComfyUI in, if you are using portable you need to use the portable's python.exe to install it, which would _not_ be `pip install sageattention`, but rather `python.exe -m pip install sageattention`, ran in the python_embeded -folder within the portable ComfyUI directory.

**Comment by CalebBarnes** [comment]
> > No module named 'sageattention'
> 
> This just means you have not installed sageattention to the same python environment you are running ComfyUI in, if you are using portable you need to use the portable's python.exe to install it, which would _not_ be `pip install sageattention`, but rather `python.exe -m pip install sageattention`, ran in the python_embeded -folder within the portable ComfyUI directory.

I tried installing it this way but for some reason still get the same error.

**Comment by parthwagh9999** [comment]
use these two commands in python virtual environment created for comfyui.
so first start that environment and then only run these commands.

python.exe -m pip install triton-windows

python.exe -m pip install sageattention

**Comment by BillySnooze** [comment]
Try  `python -m pip install sageattention==1.0.6`

**Comment by NewEpoch2020** [comment]
> Try `python -m pip install sageattention==1.0.6`

That's very helpful, thank you.

**Comment by lirexxx** [comment]
> I have solved my problem. pip3 install sageattention -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir pip3 install torch==2.5.0 torchvision==0.20.0 torchaudio==2.5.0 -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir Then, set "attention_model" to sageattn_varlen and run It work for me

Thank you! I'm running ComfyUI in Stability Matrix. It's much easier to solve the problem by clicking on three dots of the ComfyUI package > Package Commands > Install Triton and Sage Attention. Two seconds later it said "Done". I started ComfyUI and everything was working fine (check the screenshot below). :)

Update: It now takes about 5 minutes instead of 15 minutes for the exact same result (on 4090).

<img width="786" height="476" alt="Image" src="https://github.com/user-attachments/assets/fc0f66b1-57ff-4f57-b202-68d4963d5d63" />

**Comment by minhhungit** [comment]
for me I need to make sure that I use correct python.exe 

```
C:\ComfyUI_windows_portable_nvidia_cu128\python_embeded\python.exe -m pip install triton-windows
C:\ComfyUI_windows_portable_nvidia_cu128\python_embeded\python.exe -m pip install sageattention
```
