### ISSUE TITLE
Why did it run out of memory (OOM)?

### ISSUE THREAD

**Issue by JoeAu** [kijai/ComfyUI-HunyuanVideoWrapper#254]
Why did I run out of memory (OOM) when using FP8 quantization to process a 512x320 video with 85 frames? During the process, the VRAM usage remained stable at 7.4G. The GPU is an RTX 2060 with 12G of VRAM. The video generation was completed, and all 30 steps had finished, yet suddenly there was an increase in VRAM requirements at the end. Why did this happen?

`[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-01-06 19:47:27.152864
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: E:\project\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: E:\project\ComfyUI_windows_portable\ComfyUI
** Log path: E:\project\ComfyUI_windows_portable\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   2.7 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 65277 MB
pytorch version: 2.5.1+cu121
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.1+cu121 with CUDA 1201 (you have 2.5.1+cu121)
    Python  3.11.8 (you have 3.11.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\swiglu_op.py:106: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd
E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\swiglu_op.py:127: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_bwd
xformers version: 0.0.25
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
Using pytorch attention
[Prompt Server] web root: E:\project\ComfyUI_windows_portable\ComfyUI\web
E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\dual_transformer_2d.py:20: FutureWarning: `DualTransformer2DModel` is deprecated and will be removed in version 0.29. Importing `DualTransformer2DModel` from `diffusers.models.dual_transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.transformers.dual_transformer_2d import DualTransformer2DModel`, instead.
  deprecate("DualTransformer2DModel", "0.29", deprecation_message)
[Crystools INFO] Crystools version: 1.15.0
[Crystools INFO] CPU: 13th Gen Intel(R) Core(TM) i5-13400 - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 2060
[Crystools INFO] NVIDIA Driver: 560.94
### Loading: ComfyUI-Impact-Pack (V8.1.6)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.9.1)
Exception in thread Thread-13 (<lambda>):
Traceback (most recent call last):
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1351, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 995, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1026, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\resolver.py", line 36, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\base_events.py", line 867, in getaddrinfo
  File "concurrent\futures\thread.py", line 58, in run
  File "socket.py", line 962, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1408, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1400, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1387, in get_cache
    json_obj = await manager_util.get_data(uri, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_util.py", line 116, in get_data
    async with session.get(uri, headers=headers) as resp:
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 1425, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 703, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 548, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1056, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1357, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CoreMLExecutionProvider' is not in available provider names.Available providers: 'TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\Joe/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\Joe/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Joe/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\Joe/.insightface\models\buffalo_l\genderage.onnx genderage
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Joe/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)
3D OpenPose Editor: Loaded
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
### [START] ComfyUI AlekPet Nodes v1.0.39 ###
Node -> ChatGLMNode: ChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode, ChatGLM4InstructNode, ChatGLM4InstructMediaNode [Loading]
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading]
Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading]
Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading]
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading] Node -> PoseNode: PoseNode [Loading]

Node -> IDENode: IDENode [Loading]
Node -> PainterNode: PainterNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
Davemane42 Custom Nodes: Loaded
FizzleDorf Custom Nodes: Loaded
tqdm is already installed.
ImageReward is already installed.
Pillow的当前版本11.1.0满足要求，无需安装10.1.0版本。
huggingface_hub的当前版本0.24.2满足要求，无需安装0.20.1版本。
CUDA extension not installed.
CUDA extension not installed.
auto-gptq的当前版本0.7.1满足要求，无需安装0.7.1版本。
einops的当前版本0.8.0满足要求，无需安装0.7.0版本。
torchvision is already installed.
accelerate的当前版本0.29.3满足要求，无需安装0.25.0版本。
timm的当前版本0.9.16满足要求，无需安装0.9.16版本。
autoawq的当前版本0.2.3满足要求，无需安装0.2.3版本。
tiktoken is already installed.
attrdict is already installed.
einops的当前版本0.8.0满足要求，无需安装0.7.0版本。
sentencepiece的当前版本0.2.0满足要求，无需安装0.2.0版本。
deepseek_vl is already installed.
transformers的当前版本4.38.2满足要求，无需安装4.38.2版本。
accelerate的当前版本0.29.3满足要求，无需安装0.29.3版本。
bitsandbytes的当前版本0.43.1满足要求，无需安装0.43.1版本。
Crypto is already installed.
E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt\js
E:\project\ComfyUI_windows_portable\ComfyUI\web\extensions\fofo
[tinyterraNodes] Loaded
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Nvidia APEX normalization not installed, using PyTorch LayerNorm

[rgthree-comfy] Loaded 42 exciting nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 220 nodes successfully.

        "Art is the most intense mode of individualism that the world has known." - Oscar Wilde

Import times for custom nodes:
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-portrait-master-zh-cn
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CascadeResolutions
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_clip_blip_node
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ResAdapter
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\StableZero123-comfyui
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Load_Image_With_Metadata
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FLATTEN
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Native_DynamiCrafter
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.1 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.1 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.1 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Aniportrait
   0.2 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-voice2video
   0.3 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR
   0.3 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt
   0.8 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AniPortrait
   1.0 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.1 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   1.2 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DragNUWA
   1.6 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   2.8 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
  30.6 seconds: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMakerV2-ZHO

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: E:\project\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\cache\2233941102_nodes_page_1_limit_1000.json [DONE]
nightly_channel: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/cache
FETCH DATA from: E:\project\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\cache\1514988643_custom-node-list.json [DONE]
got prompt
Loading text encoder model (clipL) from: E:\project\ComfyUI_windows_portable\ComfyUI\models\clip\clip-vit-large-patch14
Text encoder to dtype: torch.float16
Loading tokenizer (clipL) from: E:\project\ComfyUI_windows_portable\ComfyUI\models\clip\clip-vit-large-patch14
Loading text encoder model (llm) from: E:\project\ComfyUI_windows_portable\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
Text encoder to dtype: torch.float16
Loading tokenizer (llm) from: E:\project\ComfyUI_windows_portable\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
llm prompt attention_mask shape: torch.Size([1, 161]), masked tokens: 31
clipL prompt attention_mask shape: torch.Size([1, 77]), masked tokens: 32
model_type FLOW
Scheduler config: FrozenDict([('num_train_timesteps', 1000), ('shift', 9.0), ('reverse', True), ('solver', 'euler'), ('n_tokens', None), ('_use_default_values', ['n_tokens', 'num_train_timesteps'])])
Using accelerate to load and assign model weights to device...
Requested to load HyVideoModel
loaded completely 9267.55071144104 9267.172119140625 False
Input (height, width, video_length) = (320, 320, 29)
Sampling 29 frames in 8 latents at 320x320 with 30 inference steps
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [08:51<00:00, 17.72s/it]
Allocated memory: memory=1.760 GB
Max allocated memory: max_memory=2.917 GB
Max reserved memory: max_reserved=3.219 GB
Decoding rows: 100%|█████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.79s/it]
Blending tiles: 100%|███████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 200.05it/s]
Prompt executed in 577.07 seconds
got prompt
llm prompt attention_mask shape: torch.Size([1, 161]), masked tokens: 75
clipL prompt attention_mask shape: torch.Size([1, 77]), masked tokens: 77
Input (height, width, video_length) = (320, 512, 85)
Sampling 85 frames in 22 latents at 512x320 with 30 inference steps
100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [50:51<00:00, 101.70s/it]
Allocated memory: memory=1.304 GB
Max allocated memory: max_memory=5.909 GB
Max reserved memory: max_reserved=7.469 GB
Decoding rows:   0%|                                                                             | 0/2 [00:00<?, ?it/s]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "E:\project\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\project\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 1239, in decode
    video = vae.decode(
            ^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 345, in decode
    decoded = self._decode(z).sample
              ^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 309, in _decode
    return self.temporal_tiled_decode(z, return_dict=return_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 536, in temporal_tiled_decode
    decoded = self.spatial_tiled_decode(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 462, in spatial_tiled_decode
    decoded = self.decoder(tile)
              ^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\vae.py", line 299, in forward
    sample = up_block(sample, latent_embeds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\unet_causal_3d_blocks.py", line 795, in forward
    hidden_states = upsampler(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\unet_causal_3d_blocks.py", line 194, in forward
    hidden_states = self.conv(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\unet_causal_3d_blocks.py", line 78, in forward
    return self.conv(x)
           ^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 725, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 720, in _conv_forward
    return F.conv3d(
           ^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 3064.77 seconds`

**Comment by 0000111100001111** [comment]
The video decode often uses more memory than the inference. Uncheck the "auto_tile_size" option in the Decode node and use e.g. 128 in spatial_tile_sample_min_size.

**Comment by PATATAJEC** [comment]
check the
![Zrzut ekranu 2025-01-06 151528](https://github.com/user-attachments/assets/d4d4bd22-dbe4-41fd-9ce8-b8508ad56928)
se settings

**Comment by PATATAJEC** [comment]
Check these settings

![Zrzut ekranu 2025-01-06 151528](https://github.com/user-attachments/assets/b8b36e89-19ba-48cc-bbff-5a2b5199ab81)

**Comment by tdrminglin** [comment]
Try to lower tempporal_tiling_sample_size to 4~8,spatial_...size to 128 , set auto_tile_size false. that may fix your problem. But I'm interested how you managed to remain the Vram use stable at 7.4G. with the same setting as yours, my 2080Ti gets OOM before sampling.

**Comment by boyan-orion** [comment]
As with the more recent updates I also got the same problem. It worked fine before with the standard txt2vid example and now i'm constantly getting OOM. The low-vram example also gives me the same issue.

With the official Comfy workflow I'm able to load the full 24GB model into my 3080 10GB GPU ( with fp8_e4m3fn ) and do 720 x 512 video with 129 frames and it works just fine by offloading 30GB+ into my system RAM.  

I even upgraded my system ram to 64GB today and the workflow won't even use more than 50% of my RAM, while the official standard Comfy workflow seems to be borrowing any amount it needs without any issue. 

Besides a GPU upgrade, maybe I'm missing something else?
