### ISSUE TITLE
Requirements for RTX 50 series?  "Assertion `false && "computeCapability not supported" in WSL2

### ISSUE THREAD

**Issue by XodrocSO** [kijai/ComfyUI-HunyuanVideoWrapper#451]
Finally got a 5090, upgraded  PyTorch Nightly 2.7, Installed Cudatoolkit 12.8, Installed Prebuilt wheels from you for Triton and SageAttention that are meant for Blackwell.

Getting:

Sampling 97 frames in 25 latents at 1280x720 with 30 inference steps
  0%|                                                                                            | 0/30 [00:00<?, ?it/s]python: /home/kijai/AI/triton/lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp:40: int mlir::triton::gpu::{anonymous}::getMMAVersionSafe(int, mlir::triton::DotOp): Assertion `false && "computeCapability not supported"' failed.

I noticed with the Pytorch nightly 3.3.0 Triton instead, I got a different error when running which was PassManager::run failed, so I assumed I needed to use your pre-built wheel.

Tried switching attention mode to sdpa and got cuda OOM errors.

normally I use ChatGPT or Grok to try to troubleshoot this stuff because I hate to bother you, but I'm left grasping at straws this time.  What am I missing?

Thanks for all your hard work.

**Comment by XodrocSO** [comment]
So turns out that compiled wheel is outdated, Kijai has uploaded a new one.  Also looks like issues with my system, I have to Undervolt to 85% power or I get a black screen driver crash/system freeze.  Run a few more tests to share, then I'll probably go ahead and close this.

**Comment by XodrocSO** [comment]
After undervolting, I'm able to use Torch Compile and Sageattn_varlen again, although currently using custom 3.3.0 Triton compile again.  Can squeeze out more frames without going OOM especially with keyframe.  I upgraded to a brand new PSU which didn't solve the need to undervolt, but don't believe this is an issue with Kijai nodes so closing this.
