### ISSUE TITLE
Processing stuck in HunynanVideo TextEncode

### ISSUE THREAD

**Issue by FlareP1** [kijai/ComfyUI-HunyuanVideoWrapper#80]
When run the Text to video example the system froze during the TextEncode stage for > 20minutes.  I think this has something to do with not using the GPU memory for the LLM test processing.  During this time CPU and GPU loading was low.  Eventually I let this continue once and it completed after >3300 seconds, but this seems excessively slow. 

I have now tried installing BitsandBytes and selecting bnb_nf4.  When I try to run the text to video example I now get the following error.

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)`

I have a system with 2x3090 and a 3080 but I run CompyUI with the following to only expose a single 3090 to the processing
```
@echo off
call .\venv\Scripts\activate.bat

set CUDA_VISIBLE_DEVICES=0
python main.py --cuda-device 0 --lowvram
```

Can you please advise what might be causeing the issue or how to debug?
Has anyone else had problems with this stage freezing?

Thanks

**Comment by FlareP1** [comment]
Full error messaage was as follows
```
The config attributes {'mid_block_causal_attn': True} were passed to AutoencoderKLCausal3D, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading text encoder model (clipL) from: C:\Users\MyUser\Documents\ComfyUI\models\clip\clip-vit-large-patch14
Text encoder to dtype: torch.float16
Loading tokenizer (clipL) from: C:\Users\MyUser\Documents\ComfyUI\models\clip\clip-vit-large-patch14
C:\Users\MyUser\Documents\ComfyUI\venv\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Loading text encoder model (llm) from: C:\Users\MyUser\Documents\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:09<00:00,  2.34s/it]
Text encoder to dtype: torch.bfloat16
Loading tokenizer (llm) from: C:\Users\MyUser\Documents\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
!!! Exception during processing !!! Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
Traceback (most recent call last):
  File "C:\Users\MyUser\Documents\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\MyUser\Documents\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 680, in process
    prompt_embeds, negative_prompt_embeds, attention_mask, negative_attention_mask = encode_prompt(self, prompt, negative_prompt, text_encoder_1)
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 579, in encode_prompt
    prompt_outputs = text_encoder.encode(text_inputs, prompt_template=prompt_template_dict, device=device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 277, in encode
    outputs = self.model(
              ^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\venv\Lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\venv\Lib\site-packages\transformers\models\llama\modeling_llama.py", line 950, in forward
    inputs_embeds = self.embed_tokens(input_ids)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\venv\Lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\venv\Lib\site-packages\torch\nn\modules\sparse.py", line 190, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "C:\Users\MyUser\Documents\ComfyUI\venv\Lib\site-packages\torch\nn\functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

Prompt executed in 13.61 seconds
```

**Comment by kijai** [comment]
> I have 96GB of RAM.
> 
> I think I have found that the `--lowvram` flag on the launch of comfyUI seams to be the problem.
> 
> When I remove that then the problem goes away. Not sure what that is doing to the memory management. I have always run with that option.
> 
> Problem fixed :-) hopefully at least this helps others out if they have the same issue? Also thanks for your great work for the community.

That's odd, I can't quickly think of anything --lowvram would affect...  I know --highvram changes the offload_device to GPU and that does affect the nodes using offload_device, but --lowvram does not affect that.
